### ISSUE TITLE
Exclude some files

### ISSUE THREAD

**Issue by IRus** [sanity/pairAdjacentViolators#1]
Hi!

Looks like you committed few directories like:

```
.idea
build
.gradle 
```

which useless for project users and auto-generated by ide or build tool. I suggest clean up this.

**Comment by sanity** [comment]
I think I've cleaned that up, please let me know if you find any other loose ends

**Comment by IRus** [comment]
Nice, thank you. Btw. i add your project to kotlin.link under Projects > Examples
