### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by IRus** [sanity/pairAdjacentViolators#5]
I want to suggest use JMH for benchmarking. It's a lot better, because JMH knows a lot about JVM, and properly warm up code, etc.

Maybe this [video is good](https://www.youtube.com/watch?v=VaWgOCDBxYw) start. 

I can help with project configuration and maybe with rewriting current benchmark to JMH.

**Comment by sanity** [comment]
Sure, while called "benchmarks", that code is mostly concerned with generating the chart displayed in README.md.  Honestly I pushed it to Github by mistake :)

**Comment by sanity** [comment]
FYI - I have renamed that package to more accurately reflect the fact that it's not a benchmark :)  It would be good to have some benchmarks though so I'll leave this ticket open.

**Comment by IRus** [comment]
Great, hope i got some time to write few of them
